resilience4j.circuitbreaker:
  instances:
    clientServiceCircuitBreaker:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 5
      minimumNumberOfCalls: 3
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      recordExceptions:
        - java.lang.Exception

spring:
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Argentina/Buenos_Aires
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

